"""Initial db setup.

Revision ID: 206cdeb487ac
Revises: 
Create Date: 2023-12-29 12:49:12.711785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206cdeb487ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_user_id'), 'todo_user', ['id'], unique=False)
    op.create_index(op.f('ix_todo_user_name'), 'todo_user', ['name'], unique=True)
    op.create_table('todo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['todo_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_item_id'), 'todo_item', ['id'], unique=False)
    op.create_index(op.f('ix_todo_item_label'), 'todo_item', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_item_label'), table_name='todo_item')
    op.drop_index(op.f('ix_todo_item_id'), table_name='todo_item')
    op.drop_table('todo_item')
    op.drop_index(op.f('ix_todo_user_name'), table_name='todo_user')
    op.drop_index(op.f('ix_todo_user_id'), table_name='todo_user')
    op.drop_table('todo_user')
    # ### end Alembic commands ###
