"""Contact list models done.

Revision ID: a5e2fedb1ee0
Revises: 
Create Date: 2024-01-04 09:01:34.092147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5e2fedb1ee0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_slug'), 'agenda', ['slug'], unique=True)
    op.create_table('todouser',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todouser_name'), 'todouser', ['name'], unique=True)
    op.create_table('contact',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todoitem',
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['todouser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todoitem')
    op.drop_table('contact')
    op.drop_index(op.f('ix_todouser_name'), table_name='todouser')
    op.drop_table('todouser')
    op.drop_index(op.f('ix_agenda_slug'), table_name='agenda')
    op.drop_table('agenda')
    # ### end Alembic commands ###
